Naming/FileName:
  Enabled: false

Style/Documentation:
  Enabled: false

Gemspec/RequiredRubyVersion:
  Enabled: false

Metrics/ClassLength:
  Max: 130

Layout/LineLength:
  Max: 161

Metrics/BlockLength:
  Max: 255

Metrics/AbcSize:
  Max: 74

Metrics/CyclomaticComplexity:
  Max: 26

Metrics/MethodLength:
  Max: 44

Metrics/PerceivedComplexity:
  Max: 26

require:
 - rubocop-rspec
 - code_scanning
