name: Run tests

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby-version: [2.6, 2.7, '3.0', 3.1, head, jruby, jruby-head]
    env:
      JRUBY_OPTS: "--debug"
    steps:
      - uses: actions/checkout@v2
      - name: Set up Ruby ${{ matrix.ruby-version }}
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby-version }}
      - name: Install dependencies
        run: bundle install
      - name: Run tests
        run: bundle exec rake spec
      - name: Coveralls Parallel
        uses: coverallsapp/github-action@1.1.3
        if: ${{ !startsWith(matrix.ruby-version, 'jruby') }}
        with:
          github-token: ${{ secrets.github_token }}
          flag-name: run-${{ matrix.ruby-version }}
          parallel: true

  finish:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Coveralls Finished
        uses: coverallsapp/github-action@1.1.3
        with:
          github-token: ${{ secrets.github_token }}
          parallel-finished: true
